@martinstolz did you run the code before the commit? : )
```bash
undefined method `fullpath' for {"fullpath"=>"/repos/ustwo/US2FormValidator"}:Hash (NoMethodError)
```

Sorry I hadn't seen this before. I'm fixing the error plus using 'mock' instead of 'mocked' since that's what we are using everywhere else.